const products=[
  {name:'Кольцо «Линия»',type:'Кольцо',position:'0% 0%',description:'Плавная форма и зеркальный блеск серебра. Акцент, который легко носить каждый день.'},
  {name:'Серьги «Капля»',type:'Серьги',position:'50% 0%',description:'Небольшие серьги с мягким органичным силуэтом.'},
  {name:'Подвеска «Тихо»',type:'Подвеска',position:'100% 0%',description:'Лаконичная подвеска, которая ловит свет при каждом движении.'},
  {name:'Серьги «Жемчуг»',type:'Серьги',position:'0% 100%',description:'Сочетание сияния металла и нежности жемчуга.'},
  {name:'Браслет «Волна»',type:'Браслет',position:'50% 100%',description:'Тонкая текучая линия вокруг запястья.'},
  {name:'Кольцо «Зеркало»',type:'Кольцо',position:'100% 100%',description:'Выразительная гладкая поверхность и чистая геометрия.'}
];
const $=s=>document.querySelector(s);const cards=$('#product-grid');let favorites=new Set(),bag=[];
function renderCards(list=products){cards.innerHTML=list.map(p=>{const i=products.indexOf(p);return `<article class="product-card"><button class="product-visual" data-product="${i}" aria-label="Подробнее: ${p.name}"><span class="product-photo" style="background-position:${p.position}"></span></button><div class="product-meta"><button class="product-name" data-product="${i}">${p.name}</button><span class="product-type">${p.type}</span></div><button class="favorite-toggle ${favorites.has(i)?'active':''}" data-favorite="${i}" aria-label="${favorites.has(i)?'Удалить из избранного':'Добавить в избранное'}: ${p.name}" aria-pressed="${favorites.has(i)}">${favorites.has(i)?'♥':'♡'}</button></article>`}).join(''); if(!list.length)cards.innerHTML='<p>По вашему запросу украшений не найдено.</p>'}
function updateCounts(){for(const [id,n] of [['favorite-count',favorites.size],['bag-count',bag.length]]){const e=$('#'+id);e.textContent=n;e.hidden=!n}}
function showDetail(i){const p=products[i];$('#detail-content').innerHTML=`<div class="detail-layout"><div class="detail-photo" role="img" aria-label="${p.name}" style="background-position:${p.position}"></div><div class="detail-copy"><p class="eyebrow">IKIRU / ${p.type.toUpperCase()}</p><h2>${p.name}</h2><p>${p.description}</p><button class="outlined-button" data-add="${i}">Добавить в корзину <span>↗</span></button></div></div>`;$('#detail-dialog').showModal()}
const info={delivery:['Доставка и оплата','Условия доставки, доступные способы оплаты и сроки будут опубликованы перед открытием продаж.'],care:['Рекомендации по уходу','Храните украшения отдельно, вдали от влаги и косметики. Протирайте мягкой сухой тканью. Для ухода за жемчугом избегайте абразивных средств.'],gift:['Подарочный сертификат','Подарочные сертификаты появятся вместе с запуском продаж.'],contact:['Контакты','Контактные данные бренда появятся здесь перед запуском магазина.']};
const docs={cookies:'Политика в отношении файлов cookie',privacy:'Политика конфиденциальности',offer:'Договор оферты'};
function showInfo(title,body){$('#info-content').innerHTML=`<div class="info-inner"><p class="eyebrow">IKIRU / ИНФОРМАЦИЯ</p><h2>${title}</h2><p>${body}</p></div>`;$('#info-dialog').showModal()}
function showList(kind){const ids=kind==='favorites'?[...favorites]:bag;const title=kind==='favorites'?'Избранное':'Корзина';$('#list-content').innerHTML=`<div class="list-inner"><p class="eyebrow">IKIRU / ВАШ ВЫБОР</p><h2>${title}</h2>${ids.length?ids.map((i,j)=>`<div class="list-item"><div class="list-thumb" style="background-position:${products[i].position}"></div><span>${products[i].name}</span><button data-remove="${kind}:${j}" aria-label="Убрать ${products[i].name}">×</button></div>`).join(''):'<p class="empty-message">Пока здесь пусто.</p>'}${kind==='bag'&&ids.length?'<p>Оформление заказов станет доступно после запуска магазина.</p>':''}</div>`;$('#list-dialog').showModal()}
renderCards();
document.addEventListener('click',e=>{const product=e.target.closest('[data-product]');if(product)showDetail(Number(product.dataset.product));const fav=e.target.closest('[data-favorite]');if(fav){const i=Number(fav.dataset.favorite);favorites.has(i)?favorites.delete(i):favorites.add(i);renderCards();updateCounts()}const add=e.target.closest('[data-add]');if(add){bag.push(Number(add.dataset.add));updateCounts();$('#detail-dialog').close();showList('bag')}const rem=e.target.closest('[data-remove]');if(rem){const [kind,j]=rem.dataset.remove.split(':');if(kind==='favorites')favorites.delete([...favorites][Number(j)]);else bag.splice(Number(j),1);updateCounts();renderCards();showList(kind)}const inf=e.target.closest('[data-info]');if(inf)showInfo(...info[inf.dataset.info]);const doc=e.target.closest('[data-doc]');if(doc)showInfo(docs[doc.dataset.doc],'Текст документа будет размещён здесь после юридического согласования и до начала приёма заказов и подписок.');if(e.target.closest('[data-close]'))e.target.closest('dialog').close()});
const menu=$('#menu-panel'),scrim=$('#scrim');function toggleMenu(open){menu.hidden=!open;scrim.hidden=!open;$('#menu-button').setAttribute('aria-expanded',String(open));if(open)$('#menu-close').focus({preventScroll:true});else $('#menu-button').focus({preventScroll:true})}$('#menu-button').addEventListener('click',()=>toggleMenu(true));$('#menu-close').addEventListener('click',()=>toggleMenu(false));scrim.addEventListener('click',()=>toggleMenu(false));menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>toggleMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden)toggleMenu(false)});
$('#favorites-button').addEventListener('click',()=>showList('favorites'));$('#bag-button').addEventListener('click',()=>showList('bag'));$('#search-button').addEventListener('click',()=>{showInfo('Поиск украшений','Введите название или вид украшения в поле ниже.');const box=$('#info-content .info-inner');box.insertAdjacentHTML('beforeend','<input class="search-input" type="search" placeholder="Например, кольцо" aria-label="Поиск по каталогу" style="width:100%;padding:13px;border:1px solid #aaa;background:white">');const input=box.querySelector('input');input.focus();input.addEventListener('input',()=>{renderCards(products.filter(p=>(p.name+' '+p.type).toLowerCase().includes(input.value.toLowerCase())))});$('#info-dialog').addEventListener('close',()=>renderCards(),{once:true})});
$('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();$('#form-message').textContent='Подписка будет доступна после запуска рассылки. Адрес не отправлен.'});
